<?php
	kumpulan_information_schema_manual();
	
	function kumpulan_information_schema_manual() {
	
		$table_apar = array(
			0=>
			array(
				"Kolom"=>"id_apar",
				"Nilai_Kolom"=>"int",
				"Tipe"=>"int",
				"Komen"=>"penting, primary"
			),
			1=>
			array(
				"Kolom"=>"id_merk",
				"Nilai_Kolom"=>"varchar(100),",
				"Tipe"=>"varchar",
				"Komen"=>"penting, fk"
			),
			2=>
			array(
				"Kolom"=>"id_jns_api",
				"Nilai_Kolom"=>"int",
				"Tipe"=>"int",
				"Komen"=>"penting, fk"
			),
			3=>
			array(
				"Kolom"=>"tipe",
				"Nilai_Kolom"=>"varchar(50),",
				"Tipe"=>"varchar",
				"Komen"=>"penting"
			),
			4=>
			array(
				"Kolom"=>"kapasitas",
				"Nilai_Kolom"=>"float",
				"Tipe"=>"float",
				"Komen"=>"penting"
			),
			5=>
			array(
				"Kolom"=>"model",
				"Nilai_Kolom"=>"varchar(50)",
				"Tipe"=>"varchar",
				"Komen"=>"",
			),
			6=>
			array(
				"Kolom"=>"diameter",
				"Nilai_Kolom"=>"float",
				"Tipe"=>"float",
				"Komen"=>"penting",
			),
			7=>
			array(
				"Kolom"=>"tinggi",
				"Nilai_Kolom"=>"float",
				"Tipe"=>"float",
				"Komen"=>"",
			),
			8=>
			array(
				"Kolom"=>"tekanan_kerja",
				"Nilai_Kolom"=>"int",
				"Tipe"=>"int",
				"Komen"=>""
			),
			9=>
			array(
				"Kolom"=>"tekanan_uji",
				"Nilai_Kolom"=>"int",
				"Tipe"=>"int",
				"Komen"=>"",
			),
			10=>
			array(
				"Kolom"=>"waktu_semprot",
				"Nilai_Kolom"=>"float",
				"Tipe"=>"float",
				"Komen"=>"penting",
			),
			11=>
			array(
				"Kolom"=>"jarak_semprot",
				"Nilai_Kolom"=>"varchar",
				"Tipe"=>"varchar",
				"Komen"=>"penting",
			),
			12=>
			array(
				"Kolom"=>"kelas_kebakaran",
				"Nilai_Kolom"=>"varchar",
				"Tipe"=>"varchar",
				"Komen"=>"penting",
			),
			13=>
			array(
				"Kolom"=>"temperatur",
				"Nilai_Kolom"=>"varchar",
				"Tipe"=>"varchar",
				"Komen"=>"penting",
			),
			14=>
			array(
				"Kolom"=>"gambar",
				"Nilai_Kolom"=>"varchar(50)",
				"Tipe"=>"varchar",
				"Komen"=>"",
			),
			15=>
			array(
				"Kolom"=>"warna",
				"Nilai_Kolom"=>"varchar(50)",
				"Tipe"=>"varchar",
				"Komen"=>"",
			),
			16=>
			array(
				"Kolom"=>"tgl_pembelian",
				"Nilai_Kolom"=>"date",
				"Tipe"=>"date",
				"Komen"=>"penting"
			)
		);
		
		return $table_apar;
	}
?>